language: rust
rust:
  - nightly

services:
  - postgresql

before_script:
  - export PATH="$HOME/.cargo/bin:$PATH"
  - echo $PATH
  - rustc -vV && cargo -vV
  - cargo install diesel_cli --no-default-features --features=postgres
  - diesel setup
script:
  - cargo test --verbose --jobs 1 #one thread prevents output mangling

env:
  global:
    - DATABASE_URL=postgres://postgres@localhost/cue_doc_test
    - DATABASE_TEST_URL=postgres://postgres@localhost/cue_doc_test