environment:
  global:
    PGUSER: postgres
    PGPASSWORD: Password12!
    MYSQL_PWD: Password12!
    DATABASE_TEST_URL: postgres://postgres:Password12!@localhost/cue_doc_test
    DATABASE_URL: postgres://postgres:Password12!@localhost/cue_doc_test
  matrix:
    - channel: nightly
      target: x86_64-pc-windows-gnu

services:
  - postgresql

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - set PATH=C:\Program Files\PostgreSQL\9.6\bin;%PATH%
  - echo %PATH%
  - rustc -vV
  - cargo -vV
  - cargo install diesel_cli --no-default-features --features=postgres

## Build Script ##

# 'cargo test' takes care of building for us, so disable Appveyor's build stage. This prevents
# the "directory does not contain a project or solution file" error.
build: false

before_test:
  - diesel setup

# Uses 'cargo test' to run tests and build. Alternatively, the project may call compiled programs
#directly or perform other testing commands. Rust will automatically be placed in the PATH
# environment variable.
test_script:
- cargo test --verbose %cargoflags%